import Head from 'next/head';

import Register from 'src/components/Auth/Register';

export default function RegisterPage() {
	return (
		<>
			<Head>
				<title>register</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Register />
		</>
	);
}
