export const ENV_VARIABLES = Object.freeze({
	BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
	API_KEY_FIREBASE: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
	AUTH_DOMAIN_FIREBASE: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
	PROJECT_ID_FIREBASE: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
	STORAGE_BUCKET_FIREBASE: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
	MESSAGING_SENDER_ID_FIREBASE: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
	APP_ID_FIREBASE: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
});
