import Head from 'next/head';

import Home from 'src/components/Home';
import { GetCurrentUserWrapper } from 'src/components/wrappers';

export default function HomePage() {
	return (
		<>
			<GetCurrentUserWrapper>
				<Head>
					<title>PSYCH</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Home />
			</GetCurrentUserWrapper>
		</>
	);
}
