import { NextPage } from 'next';
import Head from 'next/head';

import { GetCurrentAdminWrapper } from 'src/components/wrappers';
import { RouterUnAuthAdminProtectionWrapper } from 'src/components/wrappers/routerUnAuthAdminProtectionWrapper';
import LoginDoctor from 'src/screens/Doctor/LoginDoctor';

interface LoginDoctorPageProps {
	redirectUrl: string;
}

const LoginDoctorPage: NextPage<LoginDoctorPageProps> = ({ redirectUrl }) => {
	return (
		<>
			<GetCurrentAdminWrapper>
				<RouterUnAuthAdminProtectionWrapper>
					<Head>
						<title>Login</title>
						<meta name="description" content="Generated by create next app" />
						<meta name="viewport" content="width=device-width, initial-scale=1" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<LoginDoctor redirectUrl={redirectUrl} />
				</RouterUnAuthAdminProtectionWrapper>
			</GetCurrentAdminWrapper>
		</>
	);
};

LoginDoctorPage.getInitialProps = async (ctx): Promise<LoginDoctorPageProps> => {
	const redirectUrl = ctx.query.redirectUrl || '';
	return { redirectUrl: redirectUrl as string };
};

export default LoginDoctorPage;
