import { NextPage } from 'next';
import Head from 'next/head';

import Login from 'src/components/Student/Auth/Login';
import { GetCurrentUserWrapper, RouterUnAuthProtectionWrapper } from 'src/components/wrappers';

interface LoginPageProps {
	redirectUrl: string;
}

const LoginPage: NextPage<LoginPageProps> = ({ redirectUrl }) => {
	return (
		<>
			<GetCurrentUserWrapper>
				<RouterUnAuthProtectionWrapper>
					<Head>
						<title>Login</title>
						<meta name="description" content="Generated by create next app" />
						<meta name="viewport" content="width=device-width, initial-scale=1" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<Login redirectUrl={redirectUrl} />
				</RouterUnAuthProtectionWrapper>
			</GetCurrentUserWrapper>
		</>
	);
};

LoginPage.getInitialProps = async (ctx): Promise<LoginPageProps> => {
	const redirectUrl = ctx.query.redirectUrl || '';
	return { redirectUrl: redirectUrl as string };
};

export default LoginPage;
