import Head from 'next/head';

import LoginAdmin from 'src/components/Admin/Auth/Login';
import { GetCurrentAdminWrapper } from 'src/components/wrappers';
import { RouterUnAuthAdminProtectionWrapper } from 'src/components/wrappers/routerUnAuthAdminProtectionWrapper';

export default function LoginAdminPage() {
	return (
		<>
			<GetCurrentAdminWrapper>
				<RouterUnAuthAdminProtectionWrapper>
					<Head>
						<title>Login</title>
						<meta name="description" content="Generated by create next app" />
						<meta name="viewport" content="width=device-width, initial-scale=1" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<LoginAdmin />
				</RouterUnAuthAdminProtectionWrapper>
			</GetCurrentAdminWrapper>
		</>
	);
}
