import Head from 'next/head';

import LoginAdmin from 'src/components/Admin/Auth/Login';
import { RouterUnAuthProtectionWrapper } from 'src/components/wrappers';

export default function LoginAdminPage() {
	return (
		<>
			<RouterUnAuthProtectionWrapper>
				<Head>
					<title>Login</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<LoginAdmin />
			</RouterUnAuthProtectionWrapper>
		</>
	);
}
